[package]
name = "leetcode-rs"
version = "0.1.0"
edition = "2021"
authors = ["Abhyudit Jain <abhyuditjain@gmail.com>"]
description = "Leetcode solutions in Rust"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
